[package]
name = "kuchiki"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "(朽木) HTML/XML tree manipulation library"
repository = "https://github.com/SimonSapin/kuchiki"

[lib]
name = "kuchiki"
doctest = false

[dependencies]
movecell = "0.1.1"
matches = "0.1.2"
html5ever = "0.2"
string_cache = "0.1"
string_cache_plugin = "0.1"
tendril = "0.1.1"

[dev-dependencies]
tempdir = "0.3"

[dependencies.selectors]
git = "https://github.com/servo/rust-selectors"
