[package]
name = "kuchiki"
version = "0.4.3"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "(朽木) HTML/XML tree manipulation library"
repository = "https://github.com/SimonSapin/kuchiki"

[lib]
name = "kuchiki"
doctest = false

[features]
unstable = ["html5ever/unstable"]

[dependencies]
cssparser = "0.7"
matches = "0.1.4"
html5ever = "0.13.1"
html5ever-atoms = "0.2.1"
hyper = {version = ">=0.7, <0.11", optional = true}
ref_slice = "1.0"
selectors = "0.15"

[dev-dependencies]
tempdir = "0.3"
