[package]
name = "kuchiki"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "(朽木) HTML/XML tree manipulation library"
repository = "https://github.com/SimonSapin/kuchiki"

[lib]
name = "kuchiki"
doctest = false

[dependencies]
typed-arena = "1.0"
matches = "0.1.2"

[dependencies.html5ever]
git = "https://github.com/servo/html5ever"

[dependencies.string_cache]
git = "https://github.com/servo/string-cache"

[dependencies.string_cache_plugin]
git = "https://github.com/servo/string-cache"

[dependencies.selectors]
git = "https://github.com/servo/rust-selectors"
