[package]
name = "kuchiki"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "HTML/XML tree manipulation library"
repository = "https://github.com/SimonSapin/kuchiki"

[lib]
name = "kuchiki"
doctest = false

[dependencies]
rctree = "0.1"

[dependencies.html5ever]
git = "https://github.com/servo/html5ever"

[dependencies.string_cache]
git = "https://github.com/servo/string-cache"
